services:
  - type: web
    name: bangalore-house-price-predictor
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app
